#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#               Further changes by Javier Fernandez-Sanguino <jfs@debian.org>
#
# Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=mochiweb
DESC="Mochiweb web server"

APPDIR=/etc/mochiweb/apps/
DODTIME=1                   # Time to wait for the server to die, in seconds
                            # If this value is set too low you might not
                            # let some servers to die gracefully and
                            # 'restart' will not work

# Include mochiweb defaults if available
if [ -f /etc/default/mochiweb ] ; then
    . /etc/default/mochiweb
fi

set -e

mochi_start()
{
    for fl in $APPDIR/*
    do
	[ -e "$fl" ] || continue
	FL=`cat $fl | head -1`
	STARTFL="$FL/start.sh"
	OWNER=$( stat -c %U $STARTFL )

	STOPFL="$FL/stop.sh"
	STOPOWNER=$( stat -c %U $STOPFL )

	if [ $$OWNER != "root" -a -x $STARTFL -a $OWNER = $STOPOWNER ]
	then
	    su $OWNER -c $STARTFL
	fi
    done
}

mochi_stop()
{
    for fl in $APPDIR/*
    do
	[ -e "$fl" ] || continue
	FL=`cat $fl | head -1`
	STOPFL="$FL/stop.sh"
	OWNER=$( stat -c %U $STOPFL )
	if [ $OWNER != "root" -a -x $STOPFL ]
	then
	    su $OWNER -c $STOPFL
	fi
    done
}


case "$1" in
  start)
        echo -n "Starting $DESC: "
	mochi_start
        echo "$NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
	mochi_stop
        echo "$NAME."
        ;;
  restart)
    echo -n "Restarting $DESC: "
    mochi_stop
    mochi_start
        echo "$NAME."
        ;;
  *)
    N=/etc/init.d/$NAME
    # echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
    echo "Usage: $N {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
