Document: mochiweb
Title: Debian mochiweb Manual
Author: <insert document author here>
Abstract: This manual describes what mochiweb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mochiweb/mochiweb.sgml.gz

Format: postscript
Files: /usr/share/doc/mochiweb/mochiweb.ps.gz

Format: text
Files: /usr/share/doc/mochiweb/mochiweb.text.gz

Format: HTML
Index: /usr/share/doc/mochiweb/html/index.html
Files: /usr/share/doc/mochiweb/html/*.html
